### ISSUE TITLE
keepalive问题？

### ISSUE THREAD

**Issue by hesuyang11** [HalseySpicy/Geeker-Admin#163]

**Comment by hesuyang11** [comment]
> 你好，我的页面按照你的写法，当再次进入页面时，还是会请求数据？并没有缓存。![1](https://user-images.githubusercontent.com/40292517/229395790-84389885-2807-4e36-bd71-28c8b894bb93.jpg) ![2](https://user-images.githubusercontent.com/40292517/229395811-40b75619-6906-40d4-bae0-914c4b5bb6af.jpg)
> 
> 麻烦给看一下

我从其他标签页回到这个标签页，这个initList还是会请求一次。

**Comment by denganjia** [comment]
你好，你试试在script标签中加入name属性呢，这是一个区分组件的唯一值。 从 Windows 版邮件发送 发件人: 和素养发送时间: 2023年4月3日 10:11收件人: HalseySpicy/Geeker-Admin抄送: Subscribed主题: Re: [HalseySpicy/Geeker-Admin] keepalive问题？ (Issue #163) 你好，我的页面按照你的写法，当再次进入页面时，还是会请求数据？并没有缓存。 麻烦给看一下我从其他标签页回到这个标签页，这个initList还是会请求一次。—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by denganjia** [comment]
试试在组件的`script`标签中加入`name`属性，用来标识
![image](https://user-images.githubusercontent.com/46669447/229405794-b14cd9ae-8266-43e2-a686-1a1b8df373ac.png)

**Comment by haobarry** [comment]
还要这样 页面必须有名字呀

**Comment by hesuyang11** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
